import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from "@/app/providers";
import Header from "@/components/header";
import PointsParticles from "@/components/Particles/points";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',

}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="fr">
        <body>
            <Providers>
                {children}
                </Providers>
            </body>
        </html>
    )
}
